name: fashionista
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6 # Versi terbaru dari GetX
  flutter_map: ^7.0.2
  geolocator: ^9.0.1
  permission_handler: ^10.2.0
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8 # Untuk ikon Cupertino (iOS-style)
  url_launcher: ^6.3.1
  cloud_firestore: ^5.5.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Linting untuk menjaga kualitas kode

flutter:
  uses-material-design: true

  # Uncomment this section to add assets
  assets:
    - assets/images/tape1.png


  # Uncomment this section to add custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
